mozilla/remote-settings

README.md
Add info about schedule and proposed API for RemoteSettings.
=> Add more details into the README

.gitignore, docs/tutorial-local-server.rst
=> Serve attachments in the local container (fixes #75)

docs/frequently-asked-questions.rst, docs/index.rst, docs/tutorial-attachments.rst, docs/tutorial-dev-server.rst
=> Add frequently asked questions

docs/index.rst, docs/target-filters.rst
=> Add documentation about JEXL filters (fixes #82)

docs/tutorial-dev-server.rst, docs/tutorial-local-server.rst
Wait for https://github.com/mozilla-services/autograph/pull/253 to be merged, and wait for the specific user to be defined there :)
=> Add signature verification for local server

docs/frequently-asked-questions.rst
=> Add some notes about automated publication

docs/target-filters.rst
https://bugzilla.mozilla.org/show_bug.cgi?id=1615450
=> Update docs about JEXL appinfo

docs/frequently-asked-questions.rst
Updated some out of date documentation on when Remote settings synchronizes with the server.
=> Update synchronization information

docs/target-filters.rst
=> Fix #137: update snippet to manipulate local data

CHANGELOG.rst, kinto-remote-settings/README.rst, kinto-remote-settings/src/kinto_remote_settings/signer/__init__.py, kinto-remote-settings/src/kinto_remote_settings/signer/listeners.py, kinto-remote-settings/tests/signer/test_events.py, kinto-remote-settings/tests/signer/test_plugin_setup.py, kinto-remote-settings/tests/signer/test_signer_attachments.py, kinto-remote-settings/tests/signer/test_signoff_flow.py
=> Remove ability to configure group names (fixes #149)

CHANGELOG.rst, kinto-remote-settings/README.rst, kinto-remote-settings/src/kinto_remote_settings/signer/__init__.py, kinto-remote-settings/src/kinto_remote_settings/signer/utils.py, kinto-remote-settings/tests/signer/test_plugin_setup.py, kinto-remote-settings/tests/signer/test_signer.py
=> Load settings from env

requirements.in, requirements.txt
When installing `pip install kinto-remote-settings` we would pull the latest versions instead of the known good set.
=> Pin kinto-remote-settings dependencies

.circleci/config.yml, Makefile, README.rst, tests/run.sh
=> Separate browser & integration test jobs

CHANGELOG.rst, kinto-remote-settings/src/kinto_remote_settings/signer/listeners.py, kinto-remote-settings/tests/signer/test_plugin_setup.py
=> Prevent users to submit records with floats in nested arrays (fixes #218)

bin/deploy-dockerhub.sh
=> Fix #289: fix publication of latest container

RemoteSettings.Dockerfile
=> Make workdir (`/app`) home dir for user `app`

pyproject.toml, tests/browser_test.py
=> Prevent browser tests to be skipped

tests/integration/plugins/test_changes.py
Put back some assertions about changes tests, but make them less flakey
Closes #377
=> Modify strategy for changes integration test

.github/release.yml
=> Ref #418: add release notes sections

kinto-remote-settings/src/kinto_remote_settings/signer/__init__.py, kinto-remote-settings/src/kinto_remote_settings/signer/listeners.py, kinto-remote-settings/tests/signer/test_plugin_setup.py
=> Fix #435: add setting to delete preview and destination collections when source is deleted

docs/adr/adr_002_packaging_releasing_admin_UI.md, tests/browser_test.py
I thought some sequence diagrams of the release process would be helpful for this ADR. Feel free to incorporate (or not) as you see fit
=> Add sequence diagrams to ADR 2

IntegrationTests.Dockerfile, poetry.lock, pyproject.toml, tests/browser_test.py
Fixes #555. We merged the previous playwright PR early to get past our selenium issues. This PR:
1. Addresses feedback from PR #549
2. Adds review user test scenario to playwright
3. Makes browser-tests independent of each other
=> Fixes #555 - Adding additional playwright test scenario and doing a little cleanup

.github/workflows/scheduled.yaml
Fixing scheduled job PR creation. I don't know how this worked before unless github now interprets line breaks differently.
=> Fixing scheduled job PR creation

README.rst
=> Update instructions to deploy to PROD

docs/support.rst
See https://github.com/mozilla-services/shavar-list-creation/pull/197#pullrequestreview-2117817403
=> Add clarification for the basic auth value passed in automated jobs

docs/adr/adr_003_bundling_collection_data.md
[Link to document for easy viewing](https://github.com/mozilla/remote-settings/blob/adr-003/docs/adr/adr_003_bundling_collection_data.md).
=> ADR for client data bundling

.secrets.baseline, config/local.ini
This will facilitate local testing for the AMO team.
Low risk, high benefits :)
=> Backport prod settings into settings of local container

docs/client-specifications.rst
=> Add details in attachments bundles client specs docs

.github/workflows/ci.yaml, .github/workflows/publish.yaml, .github/workflows/scheduled.yaml
=> Fix publish Github Action

kinto-remote-settings/src/kinto_remote_settings/changes/utils.py, kinto-remote-settings/src/kinto_remote_settings/changes/views.py, kinto-remote-settings/tests/changes/test_changeset.py
=> Fix #767: bound provided `?_limit` in `/changeset` endpoints

kinto-remote-settings/src/kinto_remote_settings/signer/listeners.py, kinto-remote-settings/tests/signer/test_plugin_setup.py
=> Fix #745: catch error if the related objects are already deleted

.github/workflows/publish.yaml
This should fix the failing login on Docker on Dependabot PRs
=> Skip failing login on fork PRs

config/local.ini, config/testing.ini, poetry.lock, pyproject.toml
This will add request IDs to all log messages
=> Upgrade kinto to 20.1.0

kinto-remote-settings/src/kinto_remote_settings/changes/views.py, kinto-remote-settings/tests/changes/test_changeset.py
=> Fix #805: prevent crash when since value contains trailing new line

Makefile, bin/list-target-filters.py
```
$ python bin/list-target-filters.py
env.appinfo.ID == "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"
env.appinfo.ID == "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}" && env.version|versionCompare("128.0a1") <= 0
env.appinfo.ID == "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}" && env.version|versionCompare("128.0a1") > 0
env.appinfo.OS != 'Android' || env.channel != 'release'
env.channel == 'default' || env.channel == 'nightly'
env.channel == 'default' || env.channel == 'nightly' || env.channel == 'beta'
env.channel == 'nightly' || env.channel == 'default'
env.channel == 'release' && env.version < '118'
env.country == 'GB' && env.form_factor == 'desktop'
env.country == 'GB' && env.form_factor == 'phone'
env.country == 'GB' && env.form_factor == 'tablet'
env.country == 'US' && env.form_factor == …
```
=> Improve jexl filters reporting

config/local.ini, config/testing.ini
Fix #777
See deployed config https://github.com/mozilla-it/webservices-infra/pull/4227
=> Fix #777: use streamhandler with request ID filter

.github/workflows/ci.yaml, .readthedocs.yaml, Makefile, bin/repo-python-versions.py, cronjobs/Dockerfile
Fix #406
In 96e4e2b2b14cb560e1b4cd4df06a3fd83b0a40fb I was verifying all pyproject.toml but I find it dumb, and only targetted CI and Dockefiles
=> Fix #406: consistency of python versions in CI and Dockerfile

README.rst
=> Ref #813: add readthedocs badge

browser-tests/plugins/test_history.py, cronjobs/src/commands/refresh_signature.py, kinto-remote-settings/README.rst, kinto-remote-settings/src/kinto_remote_settings/signer/__init__.py, kinto-remote-settings/src/kinto_remote_settings/signer/utils.py, kinto-remote-settings/tests/signer/test_events.py, kinto-remote-settings/tests/signer/test_plugin_setup.py
=> Fix #191: remove notions of kinto-signer

docs/target-filters.rst
=> Fix #826: update documentation after JEXL normalization

kinto-remote-settings/src/kinto_remote_settings/changes/utils.py, kinto-remote-settings/tests/changes/test_changes.py
=> Ref #840: do not include buckets in monitor/changes if names share prefix

cronjobs/poetry.lock, cronjobs/pyproject.toml, cronjobs/src/commands/__init__.py, cronjobs/src/commands/purge_history.py, cronjobs/src/main.py, cronjobs/tests/commands/test_purge_history.py, poetry.lock
Ref #836
This would be complementary to https://github.com/mozilla-it/webservices-infra/pull/4667
We could run this once a week...
=>  Ref #836: Add core cronjob to purge old history entries

RemoteSettings.Dockerfile
Requires https://github.com/Kinto/kinto/pull/3525 first
=> Enable multiprocess collection for Prometheus

.github/workflows/ci.yaml, .secrets.baseline, browser-tests/test_endpoints.py, config/local.ini
=> Add Prometheus checks in integration tests

poetry.lock, pyproject.toml
This will fix https://mozilla.sentry.io/issues/6536934562 and https://mozilla.sentry.io/issues/6536794585/
=> Upgrade kinto to 20.6.1

browser-tests/test_endpoints.py, poetry.lock, pyproject.toml
=> Fix #852, Fix #855: upgrade Kinto to 21.0.0

docs/monitoring.rst
Ref #911 .
Updating documentation to include the ability to query/alert on logs via yardstick.
=> Ref #911 - Updating documentation on querying/alerting on logs via yardstick

.github/workflows/ingestion-job-publish.yaml
This reverts commit bba0f3e9574cadd387f5baa06e53dbfed227a04e #926
=> Revert "Add Slack notification for ingestion job success/failure (#926)"

docs/support.rst
Requires https://github.com/Kinto/kinto-wizard/pull/338
=> Reflect new kinto-wizard features in docs

git-reader/app.py, git-reader/tests/test_api.py
https://mozilla-hub.atlassian.net/browse/RMST-183
=> RMST-183: Rewrite cert chains URLs
