mozilla/remote-settings

docs/tutorial-attachments.rst

This spun out of a discussion on Slack. Collections without attachments "enabled" don't have an attachment field in edit records, which can be surprising/seem like a silent failure if you don't know what's going on.
More documentation might be needed in order to describe what you need to do to move to prod with attachments or something like that, but I thought this would be a good first step. It also isn't really clear whether this belongs as part of the kinto-admin documentation, but the kinto-admin documentation ... doesn't really exist, maybe because it's so WYSIWYG. Rather than try to define a structure there, I thought I would settle for adding something to the existing structure here.
I'm not 100% sure that these are the only requirements but I want to submit this before I forget.

A quick note about attachments in the admin tool

---

docs/getting-started.rst
docs/tutorial-multi-signoff.rst

Someone (like me) trying to figure out how to manage user permissions for a collection is likely to go to the multi-signoff tutorial. This adds a small comment at the top to redirect them to the "getting started" page.

Add reference to how to edit STAGE/PROD manifest to add users

---

docs/tutorial-dev-server.rst
docs/tutorial-local-server.rst

Fixes #108.
I wasn't really sure what to do about the `dev` environment. As far as I can tell, it's impossible to use correctly, so maybe we should just delete the whole article?

Remote Settings Dev Tools is the canonical way to switch environments

---

docs/target-filters.rst

I think this is all we need to close #111.  
During the work week it wasn't clear what the intended purpose of target filters is.  To allow for a single server side collection to serve many a small subset of user groups. 
An unintended consequence that occurred is that target filtering seems suitable for experimentation.  To be suitable we would need to maintain parity with the experiment platform's (normandy, normandy dev tools, filter objects, capabilities, suitabilities, etc) targeting feature set. 
Maintaining parity would diverge from the original purpose and create additional engineering overhead. 
This doc update is meant to make clear what the purpose and ideal usage of target filtering is.

improving wording about target filters to make their purpose clearer

---

docs/target-filters.rst

It was accidentally indented so it was included in the code block at https://remote-settings.readthedocs.io/en/latest/target-filters.html#advanced-testing-filter-expressions-in-the-browser-console

Fix text accidentally included in a code block of target-filters.rst

---

docs/getting-started.rst

This fixes the two broken links referencing how to view records of a particular collection

Fix broken bucket links on the getting started doc

---

.circleci/config.yml

Based on the filters set for `build_and_publish`, prior to this commit,
I would have expected this job to only run on tagged commits. However,
this job seemed to run on every commit, leading me to beleive the regex
provided would match an empty tag. So, the regex was changed to match a
non-empty string.
Additionaly, a filter was added so that the build_and_publish job will
only run on the "main" branch. After this commit is merged, we expect
this job to run on tagged commits or after any commit to the "main"
branch.

Only run build_and_publish on main branch or git tag

---

kinto-remote-settings/src/kinto_remote_settings/signer/__init__.py

Without this (ugly) safeguard, we try to create the resources when running `kinto migrate --ini=config.ini`, which will always crash if tables don't exist

Do not auto create resources on 'migrate'

---

.gitignore
CHANGELOG.rst
Dockerfile
Makefile
README.rst
app.wsgi
bin/run.sh
config/example.ini
config/local.ini
config/testing.ini
docs/tutorial-local-server.rst
kinto-remote-settings/src/kinto_remote_settings/signer/generate_keypair.py

Ship default configuration (fixes #151)

---

README.rst
config/example.ini
tests/browser_test.py
tests/conftest.py
tests/integration_test.py
tests/run.sh

ref #152
The goal here is to be able to run the integration tests container against a remote server. 
I added the option the skip server setup so that we can run the script without providing any admin credentials. Indeed, the `create_if_exists` behaviour works well when the provided user has creation permissions, otherwise the call to create() methods just raises 403s. By skipping setup, we allow the script to run with just editor and reviewers credentials (useful for STAGE)
Reviewing individual commits should be easier :)

Prepare running integration tests on remote server (ref #152)

---

Dockerfile
Dockerfile.Testing
Makefile
bin/deploy-dockerhub.sh
docker-compose.yml
requirements-dev.txt
tests/conftest.py
tests/integration_test.py
tests/run.sh

I don't see why the integration tests would have to inherit from the server container, and I changed it to be built from a simple python container. Less confusing IMO
If it wasn't for Selenium, the integration tests could almost even run outside docker-compose, as a plain python script.

Do not build test container from the server one

---

CHANGELOG.rst
requirements.txt

Note: the integration tests won't run on this PR (see #166).
However, once merged, we can rebase #166 on main and make sure the re-enabled tests pass there.

Upgrade kinto to 14.6.1

---

.gitignore
docker-compose.yml
pyproject.toml
requirements-dev.txt
tests/browser_test.py
tests/conftest.py
tests/integration_test.py

The integration and browser tests don't run on `main`  since 5f2437ed036d202c8311 . Pytest does not have explicit config and skips asyncio tests. 
This PR restores the Pytest config (by mounting pyproject.toml into the root tests container), and fixes a number of integration tests failures introduced in the recent refactoring PRs.
Note: review by commit recommended :)

Fix skipped integration tests

---

Makefile
docs/tutorial-local-server.rst

Apparently MacOS doesn't like the long-form `--mode` argument.
```
$ make integration-test                                                                                                                    
mkdir -p --mode=777 autograph-certs mail
mkdir: illegal option -- -
usage: mkdir [-pv] [-m mode] directory ...
```

Use -m instead of --mode for mkdir

---

.circleci/config.yml

Currently, the 3 workflows have the same jobs. But it makes the execution on CircleCI a lot more explicit.

Manage CircleCI filters explicitly for main, tags, and pull-requests

---

config/local.ini
config/testing.ini
tests/conftest.py
tests/integration_test.py

With the previous config, `uwsgi` would not listen to the configured port.
I didn't want to change the line in `run.sh` where the port is passed as CLI parameter. 
This fixes it. And should also fix https://github.com/mozilla-services/remote-settings-permissions/pull/302
To verify:
```
$ docker build . -t remotesettings:server
$ docker run --rm -p 8888:8888 remotesettings:server uwsgistart -e KINTO_INI=config/testing.ini
```
Before curl would fail reaching out localhost:8888

Fix public port in uwsgi

---

CHANGELOG.rst
Dockerfile

With this fix, the container runs uwsgi on the configured port when ran without parameter

Run uwsgi with port by default

---

CHANGELOG.rst
config/local.ini
config/testing.ini

One idea behind those example config files is to be able to run a local environment that behaves like DEV / STAGE
In DEV and STAGE, when you request a review, the preview collection timestamp is updated in the monitor/changes endpoint. 
This was not the case here.
Also, in our Rust client, when the current timestamp is not provided we fetch it from the monitor/changes endpoint. If the preview bucket is not monitored then we cannot fetch/sync the preview records after requesting a review.

Monitor all preview buckets

---

Makefile
README.rst
docker-compose.yml

I tried running the test container against the dev server according to the docs, but there were a few things are were off, so I did some tweaking according to the [`docker-compose run` docs](https://docs.docker.com/compose/reference/run/).
Additionally, I ran into an issue where data that was persisted in my Postgres container interfered with assumptions made by integration tests. This deserves to be looked at further from the actual tests, but for now I also added a line to `maintainer-clean` that will clear that volume.

Fix running tests container

---

.circleci/config.yml

Currently, we build the Remote Settings server and test containers in 3 different jobs:
- `integration_test`
- `browser_test`
- `build_and_publish`
Now, we build the containers once in a `build_containers` job, persist the containers to a [workspace](https://circleci.com/docs/2.0/workspaces/), then load containers in the jobs that need them.

Build containers once, load in tests and deploy jobs

---

.circleci/config.yml
bin/deploy-dockerhub.sh
docker-compose.yml

In addition to pushing the Remote Settings server container to https://hub.docker.com/u/mozilla/remote-settings, we now push the integration test container to https://hub.docker.com/r/mozilla/remote-settings-integration-tests.

Push integration test container to Dockerhub

---

.circleci/config.yml
Makefile

In the CircleCI jobs that run with a [Docker executor](https://circleci.com/docs/2.0/executor-intro#docker), switch from the CircleCI Python image to the official Python image -- the same image we use to build the Remote Settings container.

Switch to official Python image in CircleCI jobs that use Docker executor

---

CHANGELOG.rst
kinto-remote-settings/src/kinto_remote_settings/changes/views.py
kinto-remote-settings/tests/changes/test_changeset.py

With this pull-request, all `/changeset` endpoints will have their `Cache-Control` response header value set based on the settings, in this order of precedence:
* `kinto.{bid}.{cid}.record_cache_maximum_expires_seconds` if `?_expected` is in querystring, `kinto.{bid}.{cid}.record_cache_expires_seconds` otherwise
* `kinto.{bid}.record_cache_expires_seconds` 
* `kinto.record_cache_expires_seconds` 
This mimics the current behavior of `/records`, as implemented here:
https://github.com/Kinto/kinto/blob/f996279cdcdf9e2eedf268b71a1fbb7ebdac67ce/kinto/views/records.py#L106-L133
> Note for Sven:  The `max-age=86400` is set on redirects, when `?_since=` contains a very old value (default value of `kinto.changes.since_max_age_redirect_ttl_seconds` setting).

Add `Cache-Control` headers on all `/changeset` endpoints

---

CHANGELOG.rst
kinto-remote-settings/src/kinto_remote_settings/changes/views.py
kinto-remote-settings/tests/changes/test_changeset.py

This change will allow us to align the behavior of the GCP CDN with what we had with Cloudfront.
Indeed, CloudFront was not using this Last-Modified header, and was invalidating origin responses automatically when the TTL had elapsed.
By making sure the `Last-Modified` changes when signatures are refreshed, we make sure the GCP will invalidate the cache too when the TTL has elapsed.
Note: this is not a fix for #186. The problem described in that issue will still exist during the TTL window (configured as 1H)

Use collection timestamp in `Last-Modified` response header on `/changeset` endpoints

---

CHANGELOG.rst
kinto-remote-settings/src/kinto_remote_settings/changes/views.py
kinto-remote-settings/tests/changes/test_changeset.py

In #328 we wanted to change the `last_modified` field of the monitor/changes endpoint to make sure it's bumped when signature are refreshed.
But, accidentally this was changed for every collection (see https://github.com/mozilla/remote-settings/pull/328/files#diff-b86eadd7d9d6e3bf89c937518fbfce0b130e57e264e87a058afa47c295517908L380)
Clients signature verification fail because:
- They build a payload with the collection content using the fields of the changeset endpoint ([source](https://github.com/mozilla-services/remote-settings-client/blob/1f1878aee0aa2ee06efd1973bce2c5de1238aa16/src/client/signatures.rs#L111-L114) or [source](https://searchfox.org/mozilla-central/rev/fb9a504ca73529fa550efe488db2a012a4bf5169/services/settings/RemoteSettingsWorker.js#40-64))
- They verify that the …

Fix value of changesets' `timestamp` field

---

.circleci/config.yml
CHANGELOG.rst
IntegrationTests.Dockerfile
Makefile
RemoteSettings.Dockerfile
bin/run.sh
docker-compose.yml

This PR:
- specifies [profiles](https://docs.docker.com/compose/profiles/) for Docker compose so that, among other things, running `make start` (`docker compose up`) doesn't also spin up Selenium and the tests container
- Modifies our compose / Dockerfile setup so that we can rely on just Docker volumes to manage data for local development and integration tests
There isn't a super clean way to control permissions for named volumes, and this does add a little complexity to our Docker setup overall. But, I think it is nicer to have docker-compose manage volumes and to not have test data end up in the root directory.
- moves building the main `kinto-remote-settings` plugin to the `compile` stage
This means we don't have do repeat this step every time we change something in the project …

Use Docker-managed data volumes, profiles for managing services, other Docker tweaks

---

Makefile
docker-compose.yml

Though we landed #380, I noticed that the `sensitive_url` was still being set to `.*` ([e.g.](https://app.circleci.com/pipelines/github/mozilla/remote-settings/714/workflows/8b1dd86e-55da-4aaa-9108-41735879db61/jobs/3784?invite=true#step-105-9200)).
I think this is because [even though we were copying the top-level `pyproject.toml` to the tests container](https://github.com/mozilla/remote-settings/blob/388ba8739df8f4bcf122e9c0c60796d390dc4f3c/IntegrationTests.Dockerfile#L16), we were [mounting the `tests` volume to the container in Docker Compose](https://github.com/mozilla/remote-settings/blob/388ba8739df8f4bcf122e9c0c60796d390dc4f3c/docker-compose.yml#L88), which wouldn't include the copied `pyproject.toml`.
So now, we remove that volume mount and rebuild the `tests` container before …

Fix sensitive urls

---

tests/conftest.py
tests/integration/plugins/test_signer.py
tests/requirements.txt

Fix #400: rely on `/changeset` endpoint for signature integration tests

---

CHANGELOG.rst
kinto-remote-settings/src/kinto_remote_settings/signer/listeners.py

The `path` where a float is detected can be quite long.  Some tools like Sentry can truncate the error message so the useful error message is removed.
This makes troubleshooting more challenging and less obvious.  Moving the path to the end makes it clearer what the error is and where to start looking for the problem.

Fixes #410: Reorder float error message so path is at the end

---

CHANGELOG.rst
tests/integration/plugins/test_history.py

Otherwise calling `editor_client.get_history()` will fetch all history entries of the `main-workspace` bucket since epoch

Reduce size of downloaded history in integration tests

---

.secrets.baseline
kinto-remote-settings/src/kinto_remote_settings/signer/backends/autograph.py
kinto-remote-settings/tests/signer/test_plugin_setup.py
poetry.lock

Ref #284
After discussion with SREs, we should not fail the heartbeat if the Autograph cert expires soon.
Instead, we raise a warning.
We will on the logging integration https://docs.sentry.io/platforms/python/guides/logging/ to raise events when these warnings are sent

Ref #284: Do not let heartbeat fail if Autograph expires soon

---

.circleci/config.yml
kinto-remote-settings/setup.py

Since the DEV instance is redeployed on each commit, it should not show the latest tag in the version endpoint, but a fully qualified version (number of commits since last tag and commit hash) 
Thanks Sven for the suggestion
> note: https://github.com/mozilla-services/telescope/pull/1309 will be need for deployed versions checks to remain green

Show number of commits since last tag in version endpoint

---

.circleci/config.yml

```
$ git log
016079a8514697c0533f4778697eb1faa92b14ed (HEAD -> main, tag: 31.1.1, origin/main) Show number of commits since last tag in version endpoint (#464)
82f251c590c0576b962fe2874c333acb82138fa2 Bump sphinx from 7.2.5 to 7.2.6 (#462)
87cc8d909cebcf68b1ba935cd227b7df65186995 Upgrade to kinto 16.2.1 to remove superfluous Sentry warnings (#461)
faa96ce2ae4a2af7db80f0d5a7c85a675e1f00f4 Bump kinto from 16.1.0 to 16.2.1 (#463)
9377d90bf0197610705c44d2dcbf3a03e52801d0 Bump black from 23.7.0 to 23.9.1 (#460)
06e904c8f0b5a604e0b2313e358c619803c4e170 Bump coverage from 7.3.0 to 7.3.1 (#457)
409580ea230898018bc857beb3f26f7c99987f41 Bump pytest from 7.4.1 to 7.4.2 (#459)
e0d27f82430c89c2228c9ce60910f389a30d3aea (tag: 31.1.0) Ref #284: Do not let heartbeat fail if Autograph expires soon (#456) …
```

Do not skip current commit when describing current tagged version

---

.github/workflows/ci.yaml
Makefile

This PR adds caching for container builds for our integration and browser tests in CI.
In a recent PR on our `main` branch, browser and integration tests took roughly 5m 15s to run ([src](https://github.com/mozilla/remote-settings/actions/runs/6642086964))
On the first, uncached run of this workflow (in a fork), [we can see](https://github.com/grahamalama/remote-settings/actions/runs/6644408410) that about 2m 47s are dedicated to building our containers (minus some time to persist layers to the cache).
But [after the cache is populated](https://github.com/grahamalama/remote-settings/actions/runs/6644513916), that build time drops down to ~47s
While this is a nice improvement, one issue with the current approach is that the size of the cache is quite large at around ~770mb
Since Github …

Add caching for web / test container builds in CI

---

.github/dependabot.yml
.github/workflows/ci.yaml

Replace dependabot automation action with groups feature

---

Makefile
pyproject.toml

Pull-requests like #492 or #493 fail because the authors string isn't an email 🤷 
We don't have an official contact email, so at least let's be clear.

Fix authors string in pyproject.toml

---

tests/browser_test.py

Adding a 1 second wait to browser tests to wait for hooks to finish running.
Not 100% sure why this is an intermittent issue as I cannot reproduce the problem in my browser and reproducing locally was very difficult. Inspecting the DOM shows nothing is actually changing so likely hook state.

Adding wait for browser tests

---

.github/workflows/scheduled.yaml

Adds a workflow to automatically bump https://github.com/mozilla/remote-settings/blob/main/kinto-admin/VERSION when a new version of [Kinto Admin](https://github.com/Kinto/kinto-admin) is released.
This was more code that was expected -- happy for suggestions to make this more concise.
Here are some example runs:
- version was updated, creates a PR: https://github.com/grahamalama/remote-settings/actions/runs/7587922591/job/20669367084
- the branch already exists, so skips creating the PR: https://github.com/grahamalama/remote-settings/actions/runs/7587945169/job/20669406207
- Kinto Admin is up to date: https://github.com/grahamalama/remote-settings/actions/runs/7588102152/job/20669901216

Add Action workflow to bump Kinto Admin

---

bin/pull-kinto-admin.sh
poetry.lock
pyproject.toml

And copy the `VERSION` if not present (kinto-admin <= 3.0.3), until https://github.com/Kinto/kinto-admin/pull/3148 is merged and released

Upgrade kinto to 18.0.0

---

poetry.lock

Question: why Dependabot does not do this already? 
Most nostably:
- attrs
- dockerflow
- pytest
- sentry-sdk
- sqlalchemy
```
$ poetry show --outdated
attrs                    22.2.0    23.2.0     Classes Without Boilerplate
bcrypt                   4.0.1     4.1.2      Modern password hashing for your software and your servers
beautifulsoup4           4.12.0    4.12.3     Screen-scraping library
cachetools               5.3.0     5.3.2      Extensible memoizing collections and decorators
certifi                  2023.7.22 2023.11.17 Python package for providing Mozilla's CA Bundle.
cffi                     1.15.1    1.16.0     Foreign Function Interface for Python calling C code.
charset-normalizer       3.1.0     3.3.2      The Real First Universal Charset Detector. Open, modern and …
```

Upgrade all indirect dependencies

---

bin/pull-kinto-admin.sh
bin/update_and_install_system_packages.sh
poetry.lock
pyproject.toml

Fix #550: fix building of container on MacOS 

---

IntegrationTests.Dockerfile
docker-compose.yml
poetry.lock
pyproject.toml
tests/browser_test.py
tests/conftest.py
tests/integration/plugins/test_attachment.py
tests/integration/plugins/test_changes.py
tests/integration/plugins/test_email.py
tests/integration/plugins/test_history.py
tests/integration/plugins/test_signer.py
tests/integration/test_endpoints.py
tests/integration/utils.py
tests/run.sh

Fixes #522 by replacing selenium with playwright. These tests are simple and are meant as a general check that the kinto-admin UI exists, is accessible, and we can at least submit a review request. Detailed testing will be built out in the kinto-admin project.
Making these changes in `remote-settings` was a bit more complicated than `kinto`. Let me know if we'd like to see anything done differently.

Fixes #522 - Replacing selenium test with simple playwright test

---

.github/workflows/scheduled.yaml

Adjusting our github action workflow that updates kinto-admin. Making the request over the github API should result in a signed commit.

Sign commit generated by github action for kinto-admin update

---

.github/release.yml

Otherwise upgrades of Python versions or upgrades of key libraries are not mentionned in changelog, which is unfortunate

Include Dependabot pull-requests in changelog

---

README.rst
kinto-remote-settings/tests/signer/test_events.py
kinto-remote-settings/tests/signer/test_signoff_flow.py
tests/conftest.py
tests/test_review.py

This PR standardizes the collection config across tested environments. This should allow us to have more confidence in automated releases, which will be the next step for us.
Also ran `make format` which touched a couple unexpected files.
I ran the test container produced by this against dev as an additional check.

Standardizing browser tests between environments

---

RemoteSettings.Dockerfile
bin/pull-kinto-admin.sh

Changing the docker image used to pull the admin files. Mainly doing this so dependabot stops [creating PR's](https://github.com/mozilla/remote-settings/pull/573) for it.
Also switched to wget while here. We will now error on 404's rather than following them to the pretty error page and failing when extracting the tar.

Switching admin-pull to use alpine:3 image

---

.secrets.baseline
kinto-remote-settings/README.rst
kinto-remote-settings/src/kinto_remote_settings/signer/backends/autograph.py
kinto-remote-settings/tests/signer/test_signer.py

By default Autograph picks the first key in its config.
In order to support an ongoing certificate rotation, we were asked to specify the `keyid` explicitly in the signing payload. See https://github.com/mozilla-services/autograph/blob/main/docs/endpoints.md#signdata

Specify keyid for Autograph signing

---

kinto-remote-settings/src/kinto_remote_settings/signer/updater.py
kinto-remote-settings/tests/signer/test_updater.py

Change the original code contributed here: https://github.com/Kinto/kinto-signer/pull/163
I don't remember why (8 years ago) we had this condition for fields: `(if not set)`
Without the change of this PR, we can observe that the destination attributes are never updated.
Example:
https://firefox.settings.services.mozilla.com/v1/buckets/main-preview/collections/search-telemetry-v2
Does not contain https://github.com/mozilla-services/remote-settings-permissions/commit/a22956c3931cec03b130770708288e340128d9a3
This is required for our work on bundles https://github.com/mozilla-services/remote-settings-lambdas/pull/1474 so that the `attachment.bundle: true` flag is copied to preview and main collections.

Always copy 'schema' and 'attachment' attributes to preview and final collections

---

kinto-remote-settings/src/kinto_remote_settings/signer/updater.py
kinto-remote-settings/tests/signer/test_updater.py

Context: https://github.com/mozilla-services/remote-settings-lambdas/pull/1481
and https://bugzilla.mozilla.org/show_bug.cgi?id=1907327#c2

Copy 'flags' collection metadata field to published collections

---

kinto-remote-settings/src/kinto_remote_settings/changes/views.py
kinto-remote-settings/tests/changes/test_changeset.py

Context: #631 
This will allow the client code to get the bucket from the extracted data instead of parsing the json filename (`{bid}--{cid}`).
It will allow us to simplify this line from the build bundle job:
https://github.com/mozilla-services/remote-settings-lambdas/blob/48a4e4a2476de4ef2e16308a43a4e15c7ec51ff8/commands/build_bundles.py#L53
and just do `return all_changesets`

Add 'bucket' field to changeset metadata

---

kinto-remote-settings/src/kinto_remote_settings/signer/updater.py
kinto-remote-settings/tests/signer/test_updater.py

 Fix #655: propagate fields of collection metadata on signature refresh

---

RemoteSettings.Dockerfile
docker-compose.yml

```
WARN[0000] /Users/mathieu/Code/Mozilla/remote-settings/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Building 2.8s (32/32) FINISHED                                      docker:desktop-linux
=> [web internal] load build definition from RemoteSettings.Dockerfile                 0.0s
=> => transferring dockerfile: 2.51kB                                                  0.0s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)          0.0s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 31)         0.0s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 38)         0.0s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not …
```

Fix docker warnings

---

poetry.lock

 Fix #679: honor content-type while storing attachment on GCloud

---

poetry.lock
pyproject.toml

A lot of internal changes in Kinto around monitoring. 
Let's put this version ASAP in the hands of users, and see that at least everything works as usual.
This version introduces Prometheus, which can be enabled via configuration whenever we're ready to do so.
See https://github.com/Kinto/kinto/releases/tag/19.2.0

Upgrade to kinto 19.2.0

---

.secrets.baseline
config/local.ini

This is needed to be able to submit attachments for AMO (addons-bloomfilters). Apparently, this is the config on prod too.

Allow any file extension for attachments

---

.github/workflows/scheduled.yaml

Our scheduled job that updates the kinto-admin UI automatically does not auto-merge after we approve.
We're used to this happening so we sometimes miss that the PR is still open for a bit.
This sets the PR to auto-merge once all requirements are met, with `--squash` to squash commits.
Note: I tested these commands manually with a sandbox repo. But as with all actions changes, I'm 50/50 on this working right the first time.

Adjusting scheduled workflow to mark the PR's it creates for auto-mere with squash

---

kinto-remote-settings/src/kinto_remote_settings/signer/updater.py
kinto-remote-settings/tests/signer/test_events.py

Fix #719: fix crash in metrics when no changes to approve

---

kinto-remote-settings/src/kinto_remote_settings/changes/views.py
kinto-remote-settings/tests/changes/test_changeset.py

Mimic behaviour of `monitor/changes` records endpoint
The list of collections in the DevTools will now be sorted by `-last_modified` since the order of the list comes from the `RemoteSettings.inspect()` function ([source](https://searchfox.org/mozilla-central/rev/f53c09a22edc700ab1a9eaaf4da0f0dd9f11bff3/services/settings/remote-settings.sys.mjs#604-638))

Sort entries by `-last_modified` in monitor/changes changeset endpoint

---

config/local.ini

Since v27 this setting is not read anymore
https://github.com/mozilla/remote-settings/blob/2e6d1d2ec663481d7098f7575ea6bf8e0dabdc0d/CHANGELOG.rst#2700-2021-12-10

Clean up useless `group_check_enabled` setting from demo config

---

bin/list-target-filters.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1944609
```
env.version|versionCompare("129.0a1") >= 0 && env.version|versionCompare("130.0a1") < 0
env.appinfo.ID == "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"
env.version|versionCompare("124.0a1")>=0
env.version < 116
env.version|versionCompare("122.0a1") >= 0 && env.version|versionCompare("123.0a1") < 0
env.version|versionCompare("116.0a1") >= 0 && env.version|versionCompare("117.0a1") < 0
env.channel == 'default' || env.channel == 'nightly'
env.version|versionCompare("127.0a1") >= 0 && env.version|versionCompare("128.0a1") < 0
env.version|versionCompare("110.0a1")>=0
env.version|versionCompare("132.0a1") >= 0 && env.version|versionCompare("133.0a1") < 0
env.channel == 'release' && env.version < '118'
env.version|versionCompare('133.!') >= …
```

Add script to list all JEXL filter expressions

---

config/local.ini
kinto-remote-settings/src/kinto_remote_settings/signer/__init__.py
kinto-remote-settings/src/kinto_remote_settings/signer/utils.py
kinto-remote-settings/tests/signer/test_plugin_setup.py
kinto-remote-settings/tests/signer/test_utils.py

fixes #740
With this approach, we turn glob settings into real settings:
- expanded settings show up in root URL capabilities output
- no modification of existing code around permission verification
- only read list of collections in DB on startup and when a new collection is created
Current limitations:
- cannot use `.` in regexps to match collections names (eg `([a-zA-Z0-9_-]*)` instead of `(.*)`)
- have to use `(` `)` to enable expansions
I believe it is good enough to get started with our use case (see issue description)

Fixes #740: Expand patterns in settings

---

.github/workflows/publish.yaml

Follow-up from https://github.com/Kinto/kinto/pull/3490

Publish ARM64 Docker image

---

.github/workflows/publish.yaml

Current container publishing is broken because of #749 
```
/usr/bin/docker buildx build --file RemoteSettings.Dockerfile --iidfile /home/runner/work/_temp/docker-actions-toolkit-WTbCI7/build-iidfile-89a8531826.txt --platform linux/amd64,linux/arm64 --tag mozilla/remote-settings:v32.10.0-10-g83eb --tag mozilla/remote-settings:latest --target production --metadata-file /home/runner/work/_temp/docker-actions-toolkit-WTbCI7/build-metadata-85bfe38eca.json --push .
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/
```
According to this https://github.com/docker/setup-buildx-action it should do the job

Enable buildx to enable multiplatform builds

---

browser-tests/test_review.py

The preview collections in our deployed environments can take a few MS to sync. And this test is too fast sometimes.

Fixing test_review_existing_record browser test

---

docs/target-filters.rst

Fix #808
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1944609
In this PR, I split the whole list of JEXL filters into 3 sections:
- available in both desktop and application-services
- only application-services (stuff apparently copied from Nimbus)
- only desktop (most of the previous docs)
This way is much clearer for authors that certain JEXL filters won't work everywhere

Fix #808: reflect divergence of clients support in JEXL docs

---

.readthedocs.yaml

Ref #813 
See https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/

Add explicit sphinx config for readthedocs

---

bin/groups-history.py

Ref #804
I thought that it can be useful to keep these sorts of scripts, as they serve as examples and can easily be modified for other purposes.
* DEV: 3342 useless group history entries that can be deleted
* STAGE: 11123
* PROD: 9906
Other resources like collections or buckets are less likely to be affected by https://github.com/Kinto/kinto-wizard/pull/325

Ref #804: add script to list groups history and useless entries that can be deleted

---

cronjobs/src/commands/sync_megaphone.py

Ref #595 ?
I can see output of other cronjobs, but not this one. Align and replace by `print()`

Use print() in sync_megaphone cronjob

---

kinto-remote-settings/src/kinto_remote_settings/changes/utils.py
kinto-remote-settings/src/kinto_remote_settings/changes/views.py
kinto-remote-settings/tests/changes/test_utils.py
poetry.lock
pyproject.toml

Fix #830
With PROD database, loading `curl 'localhost:8888/v1/buckets/monitor/collections/changes/changeset?_expected=42&_since="1743184921243"'`:
(99.76% improvement 🤣)

Fix #830: remove query in a loop using new storage method of kinto 20.2.0

---

.secrets.baseline
kinto-remote-settings/src/kinto_remote_settings/signer/listeners.py
kinto-remote-settings/tests/signer/config.ini
kinto-remote-settings/tests/signer/test_plugin_setup.py
poetry.lock
pyproject.toml

Fix #842: prevent automatically deleted collections to show up in monitor/changes

---

cronjobs/src/commands/sync_megaphone.py
cronjobs/tests/commands/test_sync_megaphone.py

A more elegant way would have been to do https://github.com/mozilla-it/webservices-infra/pull/4566
But @freshstrangemusic said that some change would have to be done if the `nimbus-preview` collection is not listed in the monitor/changes endpoint.
Slightly modifying the `sync_megaphone` cronjob without fully hardcoding the nimbus collection seems acceptable and will stop boardcasting push notifs everytime the team publishes changes for the QA team.
The collection has very frequent changes:
```
curl -s https://telescope.prod.webservices.mozgcp.net/checks/remotesettings-prod/latest-approvals | jq '.data[]
| select(.source | contains("nimbus-preview"))
| ((.datetime // "") | tostring)
+ " +" + ((.changes.create // "0") | tostring)
+ " ~" + ((.changes.update // "0") | tostring)
+ " -" + …
```

Skip push notifications for nimbus-preview

---

.github/workflows/publish.yaml

Fix #793
Should we notify on success? I'd say we don't since we have Argo doing it already.

Fix #793: notify devs when build/publish fails

---

config/testing.ini

Calling `POST /__flush__` to reset the full content can be useful when testing clients etc.

Add flush plugin to testing config

---

docs/monitoring.rst

We are getting a warning on docs build for sql code blocks that have the `$__timeFilter` grafana parameter.
Removing the sql type from the code blocks.

fix - fixing doc warnings for highlighting failures on grafana sql blocks

---

.github/workflows/publish.yaml

Ref #897 - re-tagging the existing server image on release rather than rebuilding.
Core cronjob and browser tests images only use `latest` tags, adjusting so they aren't rebuilt on release.

Ref #897 - Adjust server release process to only re-tag on release rather than rebuild

---

.github/workflows/scheduled.yaml

Would that allow our publish action to run for the commit on `main` after merge? 
**update**: Add context:
- we have a Github action that runs on schedule every day and creates PRs ([like this one](https://github.com/mozilla/remote-settings/pull/945)) if a new version of the Kinto Admin was published
- Side note: on these PRs, Github Actions don't run, because the PR is created by a Github Action ([example](https://github.com/orgs/community/discussions/57484))
- The PR is created with "automerge" option, so as soon it gets approved, it's merged automatically
- When this happened last time ([ref](https://github.com/mozilla/remote-settings/pull/945#pullrequestreview-3019082035)), the publish github action didn't run for the merge commit that landed on `main` …

Do not automerge kinto-admin PRs

---

kinto-remote-settings/src/kinto_remote_settings/changes/views.py
kinto-remote-settings/tests/changes/test_changes.py
kinto-remote-settings/tests/changes/test_changeset.py

Ref #977 - Rejecting requests with `_expected` values lower than `_since` values. This will prevent a rare problem with them trying to go back in time.

Fix #977 - Returning 400 responses to clients when `_expected` value is less than `_since` value

---

git-reader/Dockerfile
git-reader/app.py
git-reader/mimetypes.txt
git-reader/tests/test_api.py

Alternatively we could save the original attachment metadata in tree. But this seems a reasonable approach.
It does not work on attachments that are uploaded without file extension, but these are really rare (tracking protection lists for example).
Note that for our readers, clients would still download attachments from the GCS via the CDN, with their appropriate mimetype.
Related: https://github.com/Kinto/kinto-admin/issues/3367

Git reader: serve attachments with their mimetypes

---

cronjobs/Dockerfile
cronjobs/src/commands/build_bundles.py
cronjobs/src/commands/git_export.py
cronjobs/src/main.py

Before:
```
python main.py help
Remote Settings lambdas.
Available commands:
- git_export:
Main entrypoint
- backport_records: Backport records creations, updates and deletions from one collection to another.
- build_bundles:
Main command entry point that:
- fetches all collections changesets
- builds a `changesets.json.mozlz4`
- builds a `startup.json.mozlz4`
- fetches attachments of all collections with bundle flag
- builds `{bid}--{cid}.zip` for each of them
- send the bundles to the Cloud storage bucket
- refresh_signature: Refresh the signatures of each collection.
- purge_history: Purge old history entries on a regular basis.
```
After:
```
python main.py help
Remote Settings lambdas.
Available commands:
- git_export: Export Remote Settings data to a Git repository.
- …
```

Fix cronjobs help command
